# Generated by Django 5.2 on 2025-04-15 19:21

import django.core.validators
import django.db.models.deletion
import shared
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('worker', 'Worker'), ('technician', 'Technician')], default=
                shared.RoleEnum['WORKER'], max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2)])),
                ('surname', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventio_auth.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
