# Generated by Django 5.1.7 on 2025-03-29 19:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2)])),
                ('surname', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2)])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventio_auth.role')),
            ],
        ),
    ]
