# Generated by Django 5.2 on 2025-05-01 18:30

import django.core.validators
import shared
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventio_auth', '0002_role_role_name_worker_or_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2), shared.no_only_digits]),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2), shared.no_only_digits]),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('email__regex', '^[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,}$')), name='valid_email_format'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^[^\\W\\d_]{2,}$')), name='name_min_length_2_and_only_letters'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('surname__regex', '^[^\\W\\d_]+-[^\\W\\d_]+$'), ('surname__regex', '^[^\\W\\d_]{2,}$'), _connector='OR'), name='surname_min_length_2_and_only_letters'),
        ),
    ]
