# Generated by Django 5.2 on 2025-05-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventio_auth', '0003_alter_account_name_alter_account_surname_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='surname_min_length_2_and_only_letters',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('surname__regex', '^[^\\W\\d_]{2,}$'), ('surname__regex', '^[^\\W\\d_]+-[^\\W\\d_]+$'), _connector='OR'), name='surname_min_length_2_and_only_letters'),
        ),
    ]
