# Generated by Django 5.2 on 2025-05-01 08:08

import django.core.validators
import hardware.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(2), hardware.validators.no_only_digits]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(2), hardware.validators.no_only_digits]),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^.{2,}$')), name='brand_name_min_length_2'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^\\d+$'), _negated=True), name='brand_name_not_only_digits'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_brand_name'),
        ),
    ]
