# Generated by Django 5.2 on 2025-05-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^.{2,}$')), name='category_name_min_length_2'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^\\d+$'), _negated=True), name='category_name_not_only_digits'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category_name'),
        ),
    ]
