# Generated by Django 5.2 on 2025-05-01 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_category_category_name_min_length_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('serial_number',), name='unique_serial_number'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('year_of_production__gte', 1950)), name='year_of_production_min_value'),
        ),
    ]
