# Generated by Django 5.2 on 2025-05-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_alter_device_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brand',
            name='unique_brand_name',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_serial_number',
        ),
    ]
