# Generated by Django 5.2 on 2025-05-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_remove_brand_unique_brand_name_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "hardware_device"
                ADD CONSTRAINT "year_not_greater_than_current_year"
                CHECK (year_of_production <= EXTRACT(YEAR FROM CURRENT_DATE));
            """,
            reverse_sql="""
            ALTER TABLE "hardware_device"
                DROP CONSTRAINT "year_not_greater_than_current_year";
            """
        )
    ]
