# Generated by Django 5.2.1 on 2025-05-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_alter_device_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='category_id',
            new_name='category',
        ),
    ]
