# Generated by Django 5.2.1 on 2025-05-19 21:43

import django.core.validators
import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_rename_brand_id_device_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='year_of_production',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), shared.validators.not_greater_than_current_year]),
        ),
    ]
