# Generated by Django 5.2.1 on 2025-05-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktaking',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='stocktaking',
            old_name='returned_by',
            new_name='taken_back_by',
        ),
        migrations.RenameField(
            model_name='stocktaking',
            old_name='user_id',
            new_name='user',
        ),
    ]
