# Generated by Django 5.2.1 on 2025-05-21 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0002_rename_device_id_stocktaking_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktaking',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
