name: Build and Deploy

on:
  push:
    branches:
      - production
    paths:
      - '**'
      - '.github/workflows/inventiobackend--build-and-deploy.yaml'
  workflow_dispatch:

  env:
    REGISTRY: docker.io
    IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/inventio
    RESOURCE_GROUP: Inventio
    RESOURCE_NAME: inventiobackend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:latest

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Container Apps
        run: az containerapp update --name ${{ env.RESOURCE_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --image ${{ env.IMAGE_NAME }}:latest