name: Build and Deploy

on:
  push:
    branches:
      - production
    paths:
      - '**'
      - '.github/workflows/inventiobackend--build-and-deploy.yaml'
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/inventio
      RESOURCE_GROUP: Inventio
      RESOURCE_NAME: inventiobackend

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:latest

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: docker.io/${{ env.IMAGE_NAME }}:latest
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
          containerAppName: ${{ env.RESOURCE_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          targetPort: 8000
          containerAppEnvironment: |
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            ACCESS_TOKEN_LIFETIME_MINUTES=60
            REFRESH_TOKEN_LIFETIME_DAYS=7
            SEED_TECHNICIAN1_EMAIL=${{ secrets.SEED_TECHNICIAN1_EMAIL }}
            SEED_TECHNICIAN1_PASSWORD=${{ secrets.SEED_TECHNICIAN1_PASSWORD }}
            SEED_TECHNICIAN2_EMAIL=${{ secrets.SEED_TECHNICIAN2_EMAIL }}
            SEED_TECHNICIAN2_PASSWORD=${{ secrets.SEED_TECHNICIAN2_PASSWORD }}
            SEED_WORKER1_EMAIL=${{ secrets.SEED_WORKER1_EMAIL }}
            SEED_WORKER1_PASSWORD=${{ secrets.SEED_WORKER1_PASSWORD }}
            SEED_WORKER2_EMAIL=${{ secrets.SEED_WORKER2_EMAIL }}
            SEED_WORKER2_PASSWORD=${{ secrets.SEED_WORKER2_PASSWORD }}
